import { useRef } from "react";
import Head from "next/head";
import Image from "next/image";
import { useRouter } from "next/router";
import { SearchIcon, MicrophoneIcon } from "@heroicons/react/solid";

import Header from "../components/Header";
import Footer from "../components/Footer";

export default function Home() {
  const router = useRouter();
  const searchInputRef = useRef(null);

  const search = e => {
    e.preventDefault();
    const term = searchInputRef.current.value.trim();
    if (!term) return;
    router.push(`/search?term=${term}`);
  };

  return (
    <div>
      <Head>
        <title>Google Search</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      {/* Header */}
      <Header />

      {/* Body */}
      <form className='flex flex-col items-center mt-40'>
        <Image
          src='https://upload.wikimedia.org/wikipedia/commons/thumb/2/2f/Google_2015_logo.svg/2560px-Google_2015_logo.svg.png'
          objectFit='cover'
          width='300'
          height='100'
          alt='Google Logo'
        />
        <div className='flex w-full mt-5 mx-auto max-w-[90%] border border-gray-200 hover:shadow-lg focus-within:shadow-lg px-5 py-3 rounded-full items-center sm:max-w-xl lg:max-w-2xl'>
          <SearchIcon className='h-5 text-gray-500 mr-3' />
          <input
            type='text'
            ref={searchInputRef}
            className='flex-grow focus:outline-none'
          />
          <MicrophoneIcon className='h-5' />
        </div>
        {/* buttons div */}
        <div className='flex flex-col sm:flex-row w-[50%] space-y-2 mt-8 sm:space-y-0 justify-center sm:space-x-2'>
          <button className='btn' onClick={search}>
            Google Search
          </button>
          <button className='btn'>I&apos;m Feeling Lucky</button>
        </div>
      </form>

      {/* Footer */}

      <Footer />
    </div>
  );
}
