import Head from "next/head";
import Header from "../components/Header";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Google Search</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      {/* Header */}
      <Header />
      {/* Body */}
      <h1 className='text-3xl font-bold underline'>Hi there!</h1>
      {/* Footer */}
    </div>
  );
}
